AWSTemplateFormatVersion: '2010-09-09'

Description: My simple s3 stack

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: mycfndemobucket2022